### ISSUE TITLE
[Feature request] Denomination in Fiat

### ISSUE THREAD

**Issue by DoktorShift** [lnbits/events#22]
### [ISSUE]
When creating tickets for future event i can only select sats as price. For some fiat people its to volatile. Even it´s to much work to track it down in your books when fiat denominated in sats every time have another value.

**[Solution]**
Add other fiat currencys for pricing tickets/products

[Version]
lnbits 0.11.3
events 0.1.3

**Comment by talvasconcelos** [comment]
Latest version already has fiat tickets

**Comment by dni** [comment]
closing
