### ISSUE TITLE
[Feature request] Add display picture

### ISSUE THREAD

**Issue by DoktorShift** [lnbits/events#24]
### [Issue]
When creating the ticket shelter i do not have an option to add an image for displaying my event. It would be great to have such a option.

##### Screenshot
![example picture](https://github.com/lnbits/events/assets/106493492/fa96b0aa-ccee-48c1-8366-ff3bc0d9a0a7)

This uploaded image would be displayed in the shareable ticket shelter.

**Comment by talvasconcelos** [comment]
That screenshot is from bets4sats, right?

**Comment by DoktorShift** [comment]
Thats correct

**Comment by arcbtc** [comment]
Thanks for the idea @DoktorShift, and implementing @talvasconcelos . 
you can test with https://raw.githubusercontent.com/lnbits/events/main/manifest.json
